//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Meals
    {
        public int UserMealId { get; set; }
        public int MealNumber { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MealId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual User User { get; set; }
    }
}
